In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, Embedding

In [2]:
## Dataset
dataset = [
    "သူမသည် ဖျက်သိမ်း စာကို ဖတ်နေစဉ် မျက်ရည်များ စီးကျလို့ နေသည်။",
    "အခန်းသည် သူမ မရှိခြင်းကြောင့် တိတ်ဆိတ်မှု တို့ဖြင့် လွှမ်းမိုး စေခဲ့သည်။",
    "သူသည် အလင်း မရှိသော နေရာတွင် တစ်ယောက်တည်း ထိုင်ပြီး ဝမ်းနည်းမှု ၏ အငွေ့အသက်ကို ခံစား နေသည်။",
    "သူမ၏ နှလုံးသားသည် မပြောလိုက်သော စကားများ၏ နာကျင်မှု ကြောင့် ဝမ်းနည်း နေသည်။",
    "မိုးသည် သူမ၏ စိတ်ခံစားချက်ကို စာနာပြီး ဝမ်းနည်းစွာ ကောင်းကင်မှ မျက်ရည်စက်များ အဖြစ် ရွာချပေးလို့ နေသည်။",

    "သူ၏ အပြုံးက တစ်ခန်းလုံးကို ထွန်းလင်းစေပြီး သူမ၏ နှလုံးသားကို ပူနွေး စေခဲ့သည်။",
    "သူမနှင့် တွေ့ဆုံတိုင်း ခံစားချက် တို့သည် အိမ်မက် တစ်ခု အလား အလွန်ပင် သာယာလှပလို့ နေသည်။",
    "အချစ်၏ စွမ်းအား တို့သည် ချစ်သူ နှစ်ဦး ကြားရှိ အကွာအဝေးကို ဖျက်ဆီးပစ်နိုင်သည်။",
    "အချစ်သည် သက်တမ်းမဲ့ တန်ခိုး တစ်ခု ဖြစ်ပြီး နှလုံးသားများကို နူးညံ့စေသည်။",
    "အချစ်ကို သန့်ရှင်းစွာ ထိန်းသိမ်းနိုင်ပါက ဘဝ၏ အလှတရားကို ခံစားရမည်။",

    "သူ၏ လက်သီးကို ကျစ်ကျစ် ဆုတ်ထားပြီး ရန်ငြိုးကို ထိန်းထားရန် ကြိုးစားနေသည်။",
    "သူမသည် တံခါးကို ပိတ်ချပြီး ဆူညံစွာ အော်ဟစ်လို့ နေသည်။",
    "သူ၏ မျက်လုံးများတွင် ဒေါသ စိတ် တို့ဖြင့် မီးဟုန်းဟုန်း လောင်နေသည်။",
    "အငြင်းပွားမှု သည် မာနကြောင့် တိုး၍ တိုး၍ လာသည်။",
    "သူမ၏ အသံသည် စိတ်ဆိုးမှု ကြောင့် တုန်လှုပ်နေပြီး စူးစိမ့် လှသည်။"
]
targets = ["Sadness", "Sadness", "Sadness", "Sadness", "Sadness", "Love", "Love", "Love", "Love", "Love", "Anger", "Anger", "Anger", "Anger", "Anger"]

## Convert the target labels to numerical values
target_mapping = {"Sadness": 0, "Love": 1, "Anger": 2}
encoded_lbls = np.array([target_mapping[target] for target in targets])
print(f"Encoded Labels : {encoded_lbls}")

Encoded Labels : [0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [3]:
## Apply One Hot
vocab_size = 100
encoded_sentences = [one_hot(i, vocab_size) for i in dataset]
print(f"Encoded Sentences : {encoded_sentences}")

Encoded Sentences : [[33, 13, 81, 94, 23, 54, 99], [76, 58, 44, 7, 42, 8, 28], [35, 39, 67, 69, 51, 66, 49, 38, 97, 44, 99], [60, 49, 3, 96, 27, 70, 38, 99], [75, 60, 53, 93, 62, 45, 12, 60, 61, 99], [70, 5, 39, 44, 60, 68, 37, 28], [18, 98, 21, 63, 93, 70, 52, 57, 70, 99], [50, 3, 63, 26, 68, 43, 16, 48], [75, 33, 63, 70, 92, 76, 10], [11, 26, 65, 85, 41, 81], [70, 53, 25, 56, 17, 73, 70], [33, 79, 38, 63, 50, 99], [70, 98, 97, 20, 42, 17, 27], [86, 69, 93, 76, 76, 43], [60, 79, 49, 70, 72, 11, 97]]


In [7]:
## Apply Padding
max_length = 15
pad_sentences = pad_sequences(encoded_sentences, maxlen=max_length, padding='pre')
print(f"Padding : {pad_sentences}")

Padding : [[ 0  0  0  0  0  0  0  0 33 13 81 94 23 54 99]
 [ 0  0  0  0  0  0  0  0 76 58 44  7 42  8 28]
 [ 0  0  0  0 35 39 67 69 51 66 49 38 97 44 99]
 [ 0  0  0  0  0  0  0 60 49  3 96 27 70 38 99]
 [ 0  0  0  0  0 75 60 53 93 62 45 12 60 61 99]
 [ 0  0  0  0  0  0  0 70  5 39 44 60 68 37 28]
 [ 0  0  0  0  0 18 98 21 63 93 70 52 57 70 99]
 [ 0  0  0  0  0  0  0 50  3 63 26 68 43 16 48]
 [ 0  0  0  0  0  0  0  0 75 33 63 70 92 76 10]
 [ 0  0  0  0  0  0  0  0  0 11 26 65 85 41 81]
 [ 0  0  0  0  0  0  0  0 70 53 25 56 17 73 70]
 [ 0  0  0  0  0  0  0  0  0 33 79 38 63 50 99]
 [ 0  0  0  0  0  0  0  0 70 98 97 20 42 17 27]
 [ 0  0  0  0  0  0  0  0  0 86 69 93 76 76 43]
 [ 0  0  0  0  0  0  0  0 60 79 49 70 72 11 97]]


In [8]:
## Create ANN Model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=10, input_length=max_length))
model.add(Flatten())
model.add(Dense(3, activation='softmax'))

## Display the model summary
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 15, 10)            1000      
                                                                 
 flatten (Flatten)           (None, 150)               0         
                                                                 
 dense (Dense)               (None, 3)                 453       
                                                                 
Total params: 1,453
Trainable params: 1,453
Non-trainable params: 0
_________________________________________________________________


In [11]:
## Train Model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(pad_sentences, encoded_lbls, epochs=50)

## Model Evaluation
loss, acc = model.evaluate(pad_sentences, encoded_lbls, verbose=0)
print(f'Accuracy : {acc}, Loss : {loss}')

Epoch 1/50
1/1 [==============================] - 0s 286ms/step - loss: 0.9075 - accuracy: 1.0000
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 0.9010 - accuracy: 1.0000
Epoch 3/50
1/1 [==============================] - 0s 3ms/step - loss: 0.8946 - accuracy: 1.0000
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 0.8880 - accuracy: 1.0000
Epoch 5/50
1/1 [==============================] - 0s 2ms/step - loss: 0.8814 - accuracy: 1.0000
Epoch 6/50
1/1 [==============================] - 0s 2ms/step - loss: 0.8748 - accuracy: 1.0000
Epoch 7/50
1/1 [==============================] - 0s 3ms/step - loss: 0.8681 - accuracy: 1.0000
Epoch 8/50
1/1 [==============================] - 0s 2ms/step - loss: 0.8613 - accuracy: 1.0000
Epoch 9/50
1/1 [==============================] - 0s 2ms/step - loss: 0.8545 - accuracy: 1.0000
Epoch 10/50
1/1 [==============================] - 0s 2ms/step - loss: 0.8477 - accuracy: 1.0000
Epoch 11/50
1/1 [====================

In [12]:
## Inference Model
test = [
    "သူမ၏ နှလုံးသားသည် မပြောလိုက်သော စကားများ၏ နာကျင်မှု ကြောင့် ဝမ်းနည်း နေသည်။",
    "အချစ်သည် သက်တမ်းမဲ့ တန်ခိုး တစ်ခု ဖြစ်ပြီး နှလုံးသားများကို နူးညံ့စေသည်။",
    "အငြင်းပွားမှု သည် မာနကြောင့် တိုး၍ တိုး၍ လာသည်။"
]

encoded_test = [one_hot(txt, vocab_size) for txt in test]
pad_test = pad_sequences(encoded_test, maxlen=max_length, padding='pre')
preds = np.argmax(model.predict(pad_test, verbose=0), axis=1)

## Invert the dictionary to map values back to keys
inverse_mapping = {v: k for k, v in target_mapping.items()}
labels = [inverse_mapping[pred] for pred in preds]
print(f"Predictions : {labels}")

Predictions : ['Sadness', 'Love', 'Anger']
