In [22]:
import numpy as np

dataset = [
    "သူမသည် ဖျက်သိမ်း စာကို ဖတ်နေစဉ် မျက်ရည်များ စီးကျလို့ကျလို့ နေသည်။",
    "အခန်းသည် သူမ မရှိခြင်းကြောင့် တိတ်ဆိတ်မှုတို့ဖြင့် လွှမ်းမိုး စေခဲ့သည်။",
    "သူသည် အလင်းမရှိသော နေရာတွင် တစ်ယောက်တည်း ထိုင်ပြီး ဝမ်းနည်းမှု၏ အငွေ့အသက်ကို ခံစားနေသည်။",
    "သူမ၏ နှလုံးသားသည် မပြောလိုက်သော စကားများ၏ နာကျင်မှုကြောင့် ဝမ်းနည်းနေသည်။",
    "မိုးသည် သူမ၏ စိတ်ခံစားချက်ကို စာနာပြီး ဝမ်းနည်းစွာ ကောင်းကင်မှ မျက်စက်များ အဖြစ် ရွာချပေးလို့ နေသည်။",

    "သူ၏ အပြုံးက တစ်ခန်းလုံးကို ထွန်းလင်းစေပြီး သူမ၏ နှလုံးသားကို ပူနွေး စေခဲ့သည်။",
    "သူမနှင့် တွေ့ဆုံတိုင်း ခံစားချက်တို့သည် အိမ်မက် တစ်ခု အလား အလွန်ပင် သာယာလှပလို့ နေသည်။",
    "အချစ်၏ စွမ်းအားတို့သည် ချစ်သူ နှစ်ဦး ကြားရှိ အကွာအဝေးကို ဖျက်ဆီးပစ်နိုင်သည်။",
    "အချစ်သည် သက်တမ်းမဲ့ တန်ခိုး တစ်ခု ဖြစ်ပြီး နှလုံးသားများကို နူးညံ့စေသည်။",
    "အချစ်ကို သန့်ရှင်းစွာ ထိန်းသိမ်းနိုင်ပါက ဘဝ၏ အလှတရားကို ခံစားရမည်။",

    "သူ၏ လက်သီးကို ကျစ်ကျစ်ဆုတ်ထားပြီး ရန်ငြိုးကို ထိန်းထားရန် ကြိုးစားနေသည်။",
    "သူမသည် တံခါးကို ပိတ်ချပြီး ဆူညံစွာ အော်ဟစ်လို့ နေသည်။",
    "သူ၏ မျက်လုံးများတွင် ဒေါသ စိတ်တို့ဖြင့်စိတ်တို့ဖြင့် မီးဟုန်းဟုန်း လောင်နေသည်။",
    "အငြင်းပွားမှုသည် မာနကြောင့် တိုး၍ တိုး၍ လာသည်။",
    "သူမ၏ အသံသည် စိတ်ဆိုးမှုကြောင့် တုန်လှုပ်နေပြီး စူးစိမ့် လှသည်။"
]
## 0- Sadness, 1- Love, 2- Anger
lbls = np.array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [23]:
## Step 1: Construct the dictionary programmatically
def create_dictionary(dataset):    
    unique_words = set()
    max_length = 0
    for sentence in dataset:
        max_length = max(max_length, len(sentence.split()))
        for word in sentence.split():
            cleaned_word = word.strip('.').lower()
            unique_words.add(cleaned_word)
    word2idx = {word: idx + 1 for idx, word in enumerate(sorted(unique_words))}
    idx2word = {idx+1: word for idx, word in enumerate(sorted(unique_words))}
    return word2idx, idx2word, len(idx2word), max_length

word2idx, idx2word, vocab_size, max_length = create_dictionary(dataset)
print(f"Generated Dictionary: \n{idx2word}")
print(f'Vocab_Size : {vocab_size}')
print(f'Max Length : {max_length}')

Generated Dictionary: 
{1: 'ကောင်းကင်မှ', 2: 'ကျစ်ကျစ်ဆုတ်ထားပြီး', 3: 'ကြားရှိ', 4: 'ကြိုးစားနေသည်။', 5: 'ခံစားချက်တို့သည်', 6: 'ခံစားနေသည်။', 7: 'ခံစားရမည်။', 8: 'ချစ်သူ', 9: 'စကားများ၏', 10: 'စာကို', 11: 'စာနာပြီး', 12: 'စိတ်ခံစားချက်ကို', 13: 'စိတ်ဆိုးမှုကြောင့်', 14: 'စိတ်တို့ဖြင့်စိတ်တို့ဖြင့်', 15: 'စီးကျလို့ကျလို့', 16: 'စူးစိမ့်', 17: 'စေခဲ့သည်။', 18: 'စွမ်းအားတို့သည်', 19: 'ဆူညံစွာ', 20: 'တစ်ခန်းလုံးကို', 21: 'တစ်ခု', 22: 'တစ်ယောက်တည်း', 23: 'တန်ခိုး', 24: 'တိတ်ဆိတ်မှုတို့ဖြင့်', 25: 'တိုး၍', 26: 'တုန်လှုပ်နေပြီး', 27: 'တံခါးကို', 28: 'တွေ့ဆုံတိုင်း', 29: 'ထိန်းထားရန်', 30: 'ထိန်းသိမ်းနိုင်ပါက', 31: 'ထိုင်ပြီး', 32: 'ထွန်းလင်းစေပြီး', 33: 'ဒေါသ', 34: 'နာကျင်မှုကြောင့်', 35: 'နူးညံ့စေသည်။', 36: 'နေရာတွင်', 37: 'နေသည်။', 38: 'နှစ်ဦး', 39: 'နှလုံးသားကို', 40: 'နှလုံးသားများကို', 41: 'နှလုံးသားသည်', 42: 'ပိတ်ချပြီး', 43: 'ပူနွေး', 44: 'ဖတ်နေစဉ်', 45: 'ဖျက်ဆီးပစ်နိုင်သည်။', 46: 'ဖျက်သိမ်း', 47: 'ဖြစ်ပြီး', 48: 'ဘဝ၏', 49: 'မပြောလိုက်သော', 50: 'မရှိခြင်းကြောင့်', 51: 'မာနကြောင့်', 5

In [24]:
## Step 2: Encode the sentences using the generated dictionary
def encode_sentence(sentence, word2idx):
    return [word2idx.get(word.strip('.').lower(), 0) for word in sentence.split()]

## Step 3: Decode the encoded sentences back to original sentences
def decode_sentence(encoded_sentence, idx2word):
    return ' '.join(idx2word.get(num, '') for num in encoded_sentence)

encode = encode_sentence(dataset[1], word2idx)
decode = decode_sentence(encode, idx2word)

print(f"Original: {dataset[1]}")
print(f"Encoded : {encode}")
print(f"Decoded : {decode}")

Original: အခန်းသည် သူမ မရှိခြင်းကြောင့် တိတ်ဆိတ်မှုတို့ဖြင့် လွှမ်းမိုး စေခဲ့သည်။
Encoded : [77, 70, 50, 24, 62, 17]
Decoded : အခန်းသည် သူမ မရှိခြင်းကြောင့် တိတ်ဆိတ်မှုတို့ဖြင့် လွှမ်းမိုး စေခဲ့သည်။


In [25]:
## Step 4: Padding Sequences
def pad_sequences(ls, max_length, padding='pre'):
    if padding == 'pre':
        return [0] * abs((len(ls) - max_length)) + ls
    elif padding == 'post':
        return ls + [0] * abs((len(ls) - max_length))

print(f"Padding : {pad_sequences(encode, max_length, padding='post')}")

Padding : [77, 70, 50, 24, 62, 17, 0, 0, 0, 0]


In [33]:
## Step 5 : Label Encoding
encoded_dataset = [encode_sentence(sentence, word2idx) for sentence in dataset]
encoded_dataset

[[72, 46, 10, 44, 55, 15, 37],
 [77, 70, 50, 24, 62, 17],
 [74, 85, 36, 22, 31, 66, 82, 6],
 [73, 41, 49, 9, 34, 65],
 [52, 73, 12, 11, 64, 1, 54, 84, 58, 37],
 [75, 83, 20, 32, 73, 39, 43, 17],
 [71, 28, 5, 90, 21, 86, 87, 69, 37],
 [80, 18, 8, 38, 3, 76, 45],
 [79, 67, 23, 21, 47, 40, 35],
 [78, 68, 30, 48, 88, 7],
 [75, 59, 2, 57, 29, 4],
 [72, 27, 42, 19, 91, 37],
 [75, 56, 33, 14, 53, 61],
 [81, 51, 25, 25, 60],
 [73, 89, 13, 26, 16, 63]]

In [27]:
## Label Encoding with Padding
padding_encoded_dataset = np.array([pad_sequences(encode, max_length, padding='pre') for encode in encoded_dataset])
print(padding_encoded_dataset)

[[ 0  0  0 72 46 10 44 55 15 37]
 [ 0  0  0  0 77 70 50 24 62 17]
 [ 0  0 74 85 36 22 31 66 82  6]
 [ 0  0  0  0 73 41 49  9 34 65]
 [52 73 12 11 64  1 54 84 58 37]
 [ 0  0 75 83 20 32 73 39 43 17]
 [ 0 71 28  5 90 21 86 87 69 37]
 [ 0  0  0 80 18  8 38  3 76 45]
 [ 0  0  0 79 67 23 21 47 40 35]
 [ 0  0  0  0 78 68 30 48 88  7]
 [ 0  0  0  0 75 59  2 57 29  4]
 [ 0  0  0  0 72 27 42 19 91 37]
 [ 0  0  0  0 75 56 33 14 53 61]
 [ 0  0  0  0  0 81 51 25 25 60]
 [ 0  0  0  0 73 89 13 26 16 63]]


In [28]:
def cosine_similarity(A, B):
    dot_product = np.dot(A, B)
    norm_A = np.linalg.norm(A)
    norm_B = np.linalg.norm(B)
    return dot_product / (norm_A * norm_B)

similarity = cosine_similarity(padding_encoded_dataset[0], padding_encoded_dataset[1])
print("Cosine Similarity:", similarity)

Cosine Similarity: 0.5874939468288874


In [31]:
test = "အချစ်သည် အရာအားလုံးကို နူးညံ့ စေသည်။"
categories = ["Sadness", "Love", "Anger"]

encoded_test = encode_sentence(test, word2idx)
padding_encoded_test = np.array([pad_sequences(encoded_test, max_length, padding='pre')])
preds = [cosine_similarity(source, padding_encoded_test[0]) for source in padding_encoded_dataset]
print(f'Predicted Label : {categories[lbls[np.argmax(preds)]]}')

Predicted Label : Love
